version: "3.7"

networks:
  frontend:
    ipam:
      config:
        - subnet: 10.255.100.96/28
services:
  paymentcoreapi:
    build: ./
    environment:
      - TZ=Africa/Nairobi
    expose:
      - 80
    ports:
      - "80"
    networks:
        frontend:
            ipv4_address: 10.255.100.99      
  nginx:
    build: ./nginx/
    container_name: server_paymentcoreapi
    depends_on: 
      - paymentcoreapi
    ports:
      - "7702:7702"
    networks:
        frontend:
            ipv4_address: 10.255.100.98 